package org.lodder.subtools.sublibrary;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import manifold.ext.props.rt.api.val;

@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum Language {

    ABKHAZIAN("App.Language.Abkhazian", "abk"),
    AFAR("App.Language.Afar", "aar"),
    AFRIKAANS("App.Language.Afrikaans", "afr"),
    AKAN("App.Language.Akan", "aka"),
    ALBANIAN("App.Language.Albanian", "sqi"),
    AMHARIC("App.Language.Amharic", "amh"),
    ARABIC("App.Language.Arabic", "ara"),
    ARAGONESE("App.Language.Aragonese", "arg"),
    ARMENIAN("App.Language.Armenian", "hye"),
    ASSAMESE("App.Language.Assamese", "asm"),
    AVARIC("App.Language.Avaric", "ava"),
    AVESTAN("App.Language.Avestan", "ave"),
    AYMARA("App.Language.Aymara", "aym"),
    AZERBAIJANI("App.Language.Azerbaijani", "aze"),
    BAMBARA("App.Language.Bambara", "bam"),
    BASHKIR("App.Language.Bashkir", "bak"),
    BASQUE("App.Language.Basque", "eus"),
    BELARUSIAN("App.Language.Belarusian", "bel"),
    BENGALI("App.Language.Bengali", "ben"),
    BISLAMA("App.Language.Bislama", "bis"),
    BOSNIAN("App.Language.Bosnian", "bos"),
    BRETON("App.Language.Breton", "bre"),
    BULGARIAN("App.Language.Bulgarian", "bul"),
    BURMESE("App.Language.Burmese", "mya"),
    CATALAN_VALENCIAN("App.Language.Catalan-Valencian", "cat"),
    CENTRAL_KHMER("App.Language.Central-Khmer", "khm"),
    CHAMORRO("App.Language.Chamorro", "cha"),
    CHECHEN("App.Language.Chechen", "che"),
    CHICHEWA_CHEWA_NYANJA("App.Language.Chichewa-Chewa-Nyanja", "nya"),
    CHINESE("App.Language.Chinese", "zho"),
    OLD_CHURCH_SLAVONIC("App.Language.Old-Church-Slavonic", "chu"),
    CHUVASH("App.Language.Chuvash", "chv"),
    CORNISH("App.Language.Cornish", "cor"),
    CORSICAN("App.Language.Corsican", "cos"),
    CREE("App.Language.Cree", "cre"),
    CROATIAN("App.Language.Croatian", "hrv"),
    CZECH("App.Language.Czech", "ces"),
    DANISH("App.Language.Danish", "dan"),
    DIVEHI_DHIVEHI_MALDIVIAN("App.Language.Divehi_Dhivehi_Maldivian", "div"),
    DUTCH_FLEMISH("App.Language.Dutch-Flemish", "nld"),
    DZONGKHA("App.Language.Dzongkha", "dzo"),
    ENGLISH("App.Language.English", "eng"),
    ESPERANTO("App.Language.Esperanto", "epo"),
    ESTONIAN("App.Language.Estonian", "est"),
    EWE("App.Language.Ewe", "ewe"),
    FAROESE("App.Language.Faroese", "fao"),
    FIJIAN("App.Language.Fijian", "fij"),
    FINNISH("App.Language.Finnish", "fin"),
    FRENCH("App.Language.French", "fra"),
    FULAH("App.Language.Fulah", "ful"),
    GAELIC_SCOTTISH_GAELIC("App.Language.Gaelic_Scottish_Gaelic", "gla"),
    GALICIAN("App.Language.Galician", "glg"),
    GANDA("App.Language.Ganda", "lug"),
    GEORGIAN("App.Language.Georgian", "kat"),
    GERMAN("App.Language.German", "deu"),
    GREEK_MODERN("App.Language.Greek-Modern", "ell"),
    GUARANI("App.Language.Guarani", "grn"),
    GUJARATI("App.Language.Gujarati", "guj"),
    HAITIAN_HAITIAN_CREOLE("App.Language.Haitian-Haitian-Creole", "hat"),
    HAUSA("App.Language.Hausa", "hau"),
    HEBREW("App.Language.Hebrew", "heb"),
    HERERO("App.Language.Herero", "her"),
    HINDI("App.Language.Hindi", "hin"),
    HIRI_MOTU("App.Language.Hiri_Motu", "hmo"),
    HUNGARIAN("App.Language.Hungarian", "hun"),
    ICELANDIC("App.Language.Icelandic", "isl"),
    IDO("App.Language.Ido", "ido"),
    IGBO("App.Language.Igbo", "ibo"),
    INDONESIAN("App.Language.Indonesian", "ind"),
    INTERLINGUA("App.Language.Interlingua", "ina"),
    INTERLINGUE_OCCIDENTAL("App.Language.Interlingue-Occidental", "ile"),
    INUKTITUT("App.Language.Inuktitut", "iku"),
    INUPIAQ("App.Language.Inupiaq", "ipk"),
    IRISH("App.Language.Irish", "gle"),
    ITALIAN("App.Language.Italian", "ita"),
    JAPANESE("App.Language.Japanese", "jpn"),
    JAVANESE("App.Language.Javanese", "jav"),
    KALAALLISUT_GREENLANDIC("App.Language.Kalaallisut_Greenlandic", "kal"),
    KANNADA("App.Language.Kannada", "kan"),
    KANURI("App.Language.Kanuri", "kau"),
    KASHMIRI("App.Language.Kashmiri", "kas"),
    KAZAKH("App.Language.Kazakh", "kaz"),
    KIKUYU_GIKUYU("App.Language.Kikuyu-Gikuyu", "kik"),
    KINYARWANDA("App.Language.Kinyarwanda", "kin"),
    KOMI("App.Language.Komi", "kom"),
    KONGO("App.Language.Kongo", "kon"),
    KOREAN("App.Language.Korean", "kor"),
    KUANYAMA_KWANYAMA("App.Language.Kuanyama-Kwanyama", "kua"),
    KURDISH("App.Language.Kurdish", "kur"),
    KYRGYZ_KIRGHIZ("App.Language.Kyrgyz-Kirghiz", "kir"),
    LAO("App.Language.Lao", "lao"),
    LATIN("App.Language.Latin", "lat"),
    LATVIAN("App.Language.Latvian", "lav"),
    LIMBURGAN_LIMBURGER_LIMBURGISH("App.Language.Limburgan-Limburger-Limburgish", "lim"),
    LINGALA("App.Language.Lingala", "lin"),
    LITHUANIAN("App.Language.Lithuanian", "lit"),
    LUBA_KATANGA("App.Language.Luba-Katanga", "lub"),
    LUXEMBOURGISH_LETZEBURGESCH("App.Language.Luxembourgish-Letzeburgesch", "ltz"),
    MACEDONIAN("App.Language.Macedonian", "mkd"),
    MALAGASY("App.Language.Malagasy", "mlg"),
    MALAY("App.Language.Malay", "msa"),
    MALAYALAM("App.Language.Malayalam", "mal"),
    MALTESE("App.Language.Maltese", "mlt"),
    MANX("App.Language.Manx", "glv"),
    MAORI("App.Language.Maori", "mri"),
    MARATHI("App.Language.Marathi", "mar"),
    MARSHALLESE("App.Language.Marshallese", "mah"),
    MONGOLIAN("App.Language.Mongolian", "mon"),
    NAURU("App.Language.Nauru", "nau"),
    NAVAJO_NAVAHO("App.Language.Navajo-Navaho", "nav"),
    NDONGA("App.Language.Ndonga", "ndo"),
    NEPALI("App.Language.Nepali", "nep"),
    NORTH_NDEBELE("App.Language.North-Ndebele", "nde"),
    NORTHERN_SAMI("App.Language.Northern-Sami", "sme"),
    NORWEGIAN("App.Language.Norwegian", "nor"),
    NORWEGIAN_BOKMåL("App.Language.Norwegian-Bokmål", "nob"),
    NORWEGIAN_NYNORSK("App.Language.Norwegian-Nynorsk", "nno"),
    OCCITAN("App.Language.Occitan", "oci"),
    OJIBWA("App.Language.Ojibwa", "oji"),
    ORIYA("App.Language.Oriya", "ori"),
    OROMO("App.Language.Oromo", "orm"),
    OSSETIAN_OSSETIC("App.Language.Ossetian_Ossetic", "oss"),
    PALI("App.Language.Pali", "pli"),
    PASHTO_PUSHTO("App.Language.Pashto_Pushto", "pus"),
    PERSIAN("App.Language.Persian", "fas"),
    POLISH("App.Language.Polish", "pol"),
    PORTUGUESE("App.Language.Portuguese", "por"),
    PUNJABI_PANJABI("App.Language.Punjabi-Panjabi", "pan"),
    QUECHUA("App.Language.Quechua", "que"),
    ROMANIAN_MOLDAVIAN_MOLDOVAN("App.Language.Romanian-Moldavian-Moldovan", "ron"),
    ROMANSH("App.Language.Romansh", "roh"),
    RUNDI("App.Language.Rundi", "run"),
    RUSSIAN("App.Language.Russian", "rus"),
    SAMOAN("App.Language.Samoan", "smo"),
    SANGO("App.Language.Sango", "sag"),
    SANSKRIT("App.Language.Sanskrit", "san"),
    SARDINIAN("App.Language.Sardinian", "srd"),
    SERBIAN("App.Language.Serbian", "srp"),
    SHONA("App.Language.Shona", "sna"),
    SICHUAN_YI_NUOSU("App.Language.Sichuan_Yi_Nuosu", "iii"),
    SINDHI("App.Language.Sindhi", "snd"),
    SINHALA_SINHALESE("App.Language.Sinhala-Sinhalese", "sin"),
    SLOVAK("App.Language.Slovak", "slk"),
    SLOVENIAN("App.Language.Slovenian", "slv"),
    SOMALI("App.Language.Somali", "som"),
    SOUTH_NDEBELE("App.Language.South-Ndebele", "nbl"),
    SOUTHERN_SOTHO("App.Language.Southern-Sotho", "sot"),
    SPANISH_CASTILIAN("App.Language.Spanish-Castilian", "spa"),
    SUNDANESE("App.Language.Sundanese", "sun"),
    SWAHILI("App.Language.Swahili", "swa"),
    SWATI("App.Language.Swati", "ssw"),
    SWEDISH("App.Language.Swedish", "swe"),
    TAGALOG("App.Language.Tagalog", "tgl"),
    TAHITIAN("App.Language.Tahitian", "tah"),
    TAJIK("App.Language.Tajik", "tgk"),
    TAMIL("App.Language.Tamil", "tam"),
    TATAR("App.Language.Tatar", "tat"),
    TELUGU("App.Language.Telugu", "tel"),
    THAI("App.Language.Thai", "tha"),
    TIBETAN("App.Language.Tibetan", "bod"),
    TIGRINYA("App.Language.Tigrinya", "tir"),
    TONGA("App.Language.Tonga", "ton"),
    TSONGA("App.Language.Tsonga", "tso"),
    TSWANA("App.Language.Tswana", "tsn"),
    TURKISH("App.Language.Turkish", "tur"),
    TURKMEN("App.Language.Turkmen", "tuk"),
    TWI("App.Language.Twi", "twi"),
    UIGHUR_UYGHUR("App.Language.Uighur-Uyghur", "uig"),
    UKRAINIAN("App.Language.Ukrainian", "ukr"),
    URDU("App.Language.Urdu", "urd"),
    UZBEK("App.Language.Uzbek", "uzb"),
    VENDA("App.Language.Venda", "ven"),
    VIETNAMESE("App.Language.Vietnamese", "vie"),
    VOLAPüK("App.Language.Volapük", "vol"),
    WALLOON("App.Language.Walloon", "wln"),
    WELSH("App.Language.Welsh", "cym"),
    WESTERN_FRISIAN("App.Language.Western_Frisian", "fry"),
    WOLOF("App.Language.Wolof", "wol"),
    XHOSA("App.Language.Xhosa", "xho"),
    YIDDISH("App.Language.Yiddish", "yid"),
    YORUBA("App.Language.Yoruba", "yor"),
    ZHUANG_CHUANG("App.Language.Zhuang-Chuang", "zha"),
    ZULU("App.Language.Zulu", "zul");

    @val String msgCode;
    @val String iso639Set3;

//    public static Language fromValue(String value) {
//        return Language.values().stream().filter(lang -> lang.name().equalsIgnoreCase(value)).findAny().orElseThrow();
//    }
//
//    public static Optional<Language> fromValueOptional(String value) {
//        return Language.values().stream().filter(lang -> lang.name().equalsIgnoreCase(value)).findAny();
//    }
//
//    public static Optional<Language> ofLangCodeOptional(String languageId) {
//        return Language.values().stream().filter(lang -> lang.langCode.equalsIgnoreCase(languageId)).findAny();
//    }
//
//    public static Language ofLangCode(String languageId) {
//        return ofLangCodeOptional(languageId).orElseThrow();
//    }
//
//    public String getName() {
//        return name().substring(0, 1).toUpperCase() + name().substring(1).toLowerCase();
//    }


//    AFAR("App.Language.Afar", "aar"),
//    ABKHAZ("App.Language.Abkhaz", "abk"),
//    AFRIKAANS("App.Language.Afrikaans", "afr"),
//    AKAN("App.Language.Akan", "aka"),
//    AMHARIC("App.Language.Amharic", "amh"),
//    ARABIC("App.Language.Arabic", "ara"),
//    ARAGONESE("App.Language.Aragonese", "arg"),
//    ASSAMESE("App.Language.Assamese", "asm"),
//    AVARIC("App.Language.Avaric", "ava"),
//    AVESTAN("App.Language.Avestan", "ave"),
//    AYMARA("App.Language.Aymara", "aym"),
//    AZERBAIJANI("App.Language.Azerbaijani", "aze"),
//    BASHKIR("App.Language.Bashkir", "bak"),
//    BAMBARA("App.Language.Bambara", "bam"),
//    BELARUSIAN("App.Language.Belarusian", "bel"),
//    BENGALI("App.Language.Bengali", "ben"),
//    BIHARI("App.Language.Bihari", "bih"),
//    BISLAMA("App.Language.Bislama", "bis"),
//    TIBETAN_STANDARD("App.Language.Tibetan Standard", "bod"),
//    BOSNIAN("App.Language.Bosnian", "bos"),
//    BRETON("App.Language.Breton", "bre"),
//    BULGARIAN("App.Language.Bulgarian", "bul"),
//    CATALAN("App.Language.Catalan", "cat"),
//    CZECH("App.Language.Czech", "ces"),
//    CHAMORRO("App.Language.Chamorro", "cha"),
//    CHECHEN("App.Language.Chechen", "che"),
//    OLD_CHURCH_SLAVONIC("App.Language.Old Church Slavonic", "chu"),
//    CHUVASH("App.Language.Chuvash", "chv"),
//    CORNISH("App.Language.Cornish", "cor"),
//    CORSICAN("App.Language.Corsican", "cos"),
//    CREE("App.Language.Cree", "cre"),
//    WELSH("App.Language.Welsh", "cym"),
//    DANISH("App.Language.Danish", "dan"),
//    GERMAN("App.Language.German", "deu"),
//    DIVEHI("App.Language.Divehi", "div"),
//    DZONGKHA("App.Language.Dzongkha", "dzo"),
//    GREEK("App.Language.Greek", "ell"),
//    ENGLISH("App.Language.English", "eng"),
//    ESPERANTO("App.Language.Esperanto", "epo"),
//    ESTONIAN("App.Language.Estonian", "est"),
//    BASQUE("App.Language.Basque", "eus"),
//    EWE("App.Language.Ewe", "ewe"),
//    FAROESE("App.Language.Faroese", "fao"),
//    PERSIAN("App.Language.Persian", "fas"),
//    FIJIAN("App.Language.Fijian", "fij"),
//    FINNISH("App.Language.Finnish", "fin"),
//    FRENCH("App.Language.French", "fra"),
//    WESTERN_FRISIAN("App.Language.Western Frisian", "fry"),
//    FULA("App.Language.Fula", "ful"),
//    SCOTTISH_GAELIC("App.Language.Scottish Gaelic", "gla"),
//    IRISH("App.Language.Irish", "gle"),
//    GALICIAN("App.Language.Galician", "glg"),
//    MANX("App.Language.Manx", "glv"),
//    GUARANí("App.Language.Guaraní", "grn"),
//    GUJARATI("App.Language.Gujarati", "guj"),
//    HAITIAN("App.Language.Haitian", "hat"),
//    HAUSA("App.Language.Hausa", "hau"),
//    HEBREW("App.Language.Hebrew", "heb"),
//    HERERO("App.Language.Herero", "her"),
//    HINDI("App.Language.Hindi", "hin"),
//    HIRI_MOTU("App.Language.Hiri Motu", "hmo"),
//    CROATIAN("App.Language.Croatian", "hrv"),
//    HUNGARIAN("App.Language.Hungarian", "hun"),
//    ARMENIAN("App.Language.Armenian", "hye"),
//    IGBO("App.Language.Igbo", "ibo"),
//    IDO("App.Language.Ido", "ido"),
//    NUOSU("App.Language.Nuosu", "iii"),
//    INUKTITUT("App.Language.Inuktitut", "iku"),
//    INTERLINGUE("App.Language.Interlingue", "ile"),
//    INTERLINGUA("App.Language.Interlingua", "ina"),
//    INDONESIAN("App.Language.Indonesian", "ind"),
//    INUPIAQ("App.Language.Inupiaq", "ipk"),
//    ICELANDIC("App.Language.Icelandic", "isl"),
//    ITALIAN("App.Language.Italian", "ita"),
//    JAVANESE("App.Language.Javanese", "jav"),
//    JAPANESE("App.Language.Japanese", "jpn"),
//    KALAALLISUT("App.Language.Kalaallisut", "kal"),
//    KANNADA("App.Language.Kannada", "kan"),
//    KASHMIRI("App.Language.Kashmiri", "kas"),
//    GEORGIAN("App.Language.Georgian", "kat"),
//    KANURI("App.Language.Kanuri", "kau"),
//    KAZAKH("App.Language.Kazakh", "kaz"),
//    KHMER("App.Language.Khmer", "khm"),
//    KIKUYU("App.Language.Kikuyu", "kik"),
//    KINYARWANDA("App.Language.Kinyarwanda", "kin"),
//    KIRGHIZ("App.Language.Kirghiz", "kir"),
//    KOMI("App.Language.Komi", "kom"),
//    KONGO("App.Language.Kongo", "kon"),
//    KOREAN("App.Language.Korean", "kor"),
//    KWANYAMA("App.Language.Kwanyama", "kua"),
//    KURDISH("App.Language.Kurdish", "kur"),
//    LAO("App.Language.Lao", "lao"),
//    LATIN("App.Language.Latin", "lat"),
//    LATVIAN("App.Language.Latvian", "lav"),
//    LIMBURGISH("App.Language.Limburgish", "lim"),
//    LINGALA("App.Language.Lingala", "lin"),
//    LITHUANIAN("App.Language.Lithuanian", "lit"),
//    LUXEMBOURGISH("App.Language.Luxembourgish", "ltz"),
//    LUBA_KATANGA("App.Language.Luba-Katanga", "lub"),
//    LUGANDA("App.Language.Luganda", "lug"),
//    MARSHALLESE("App.Language.Marshallese", "mah"),
//    MALAYALAM("App.Language.Malayalam", "mal"),
//    MARATHI("App.Language.Marathi", "mar"),
//    MACEDONIAN("App.Language.Macedonian", "mkd"),
//    MALAGASY("App.Language.Malagasy", "mlg"),
//    MALTESE("App.Language.Maltese", "mlt"),
//    MONGOLIAN("App.Language.Mongolian", "mon"),
//    MāORI("App.Language.Māori", "mri"),
//    MALAY("App.Language.Malay", "msa"),
//    BURMESE("App.Language.Burmese", "mya"),
//    NAURU("App.Language.Nauru", "nau"),
//    NAVAJO("App.Language.Navajo", "nav"),
//    SOUTH_NDEBELE("App.Language.South Ndebele", "nbl"),
//    NORTH_NDEBELE("App.Language.North Ndebele", "nde"),
//    NDONGA("App.Language.Ndonga", "ndo"),
//    NEPALI("App.Language.Nepali", "nep"),
//    DUTCH("App.Language.Dutch", "nld"),
//    NORWEGIAN("App.Language.Norwegian", "nor"),
//    CHEWA("App.Language.Chewa", "nya"),
//    OCCITAN("App.Language.Occitan", "oci"),
//    OJIBWE("App.Language.Ojibwe", "oji"),
//    ORIYA("App.Language.Oriya", "ori"),
//    OROMO("App.Language.Oromo", "orm"),
//    OSSETIAN("App.Language.Ossetian", "oss"),
//    PANJABI("App.Language.Panjabi", "pan"),
//    PāLI("App.Language.Pāli", "pli"),
//    POLISH("App.Language.Polish", "pol"),
//    PORTUGUESE_PORTUGAL("App.Language.Portuguese - Portugal", "por"),
//    PORTUGUESE_BRAZIL("App.Language.Portuguese - Brazil", "pt"),
//    PASHTO("App.Language.Pashto", "pus"),
//    QUECHUA("App.Language.Quechua", "que"),
//    ROMANSH("App.Language.Romansh", "roh"),
//    ROMANIAN("App.Language.Romanian", "ron"),
//    KIRUNDI("App.Language.Kirundi", "run"),
//    RUSSIAN("App.Language.Russian", "rus"),
//    SANGO("App.Language.Sango", "sag"),
//    SANSKRIT("App.Language.Sanskrit", "san"),
//    SINHALA("App.Language.Sinhala", "sin"),
//    SLOVAK("App.Language.Slovak", "slk"),
//    SLOVENE("App.Language.Slovene", "slv"),
//    NORTHERN_SAMI("App.Language.Northern Sami", "sme"),
//    SAMOAN("App.Language.Samoan", "smo"),
//    SHONA("App.Language.Shona", "sna"),
//    SINDHI("App.Language.Sindhi", "snd"),
//    SOMALI("App.Language.Somali", "som"),
//    SOUTHERN_SOTHO("App.Language.Southern Sotho", "sot"),
//    SPANISH("App.Language.Spanish", "spa"),
//    ALBANIAN("App.Language.Albanian", "sqi"),
//    SARDINIAN("App.Language.Sardinian", "srd"),
//    SERBIAN("App.Language.Serbian", "srp"),
//    SWATI("App.Language.Swati", "ssw"),
//    SUNDANESE("App.Language.Sundanese", "sun"),
//    SWAHILI("App.Language.Swahili", "swa"),
//    SWEDISH("App.Language.Swedish", "swe"),
//    TAHITIAN("App.Language.Tahitian", "tah"),
//    TAMIL("App.Language.Tamil", "tam"),
//    TATAR("App.Language.Tatar", "tat"),
//    TELUGU("App.Language.Telugu", "tel"),
//    TAJIK("App.Language.Tajik", "tgk"),
//    TAGALOG("App.Language.Tagalog", "tgl"),
//    THAI("App.Language.Thai", "tha"),
//    TIGRINYA("App.Language.Tigrinya", "tir"),
//    TONGA("App.Language.Tonga", "ton"),
//    TSWANA("App.Language.Tswana", "tsn"),
//    TSONGA("App.Language.Tsonga", "tso"),
//    TURKMEN("App.Language.Turkmen", "tuk"),
//    TURKISH("App.Language.Turkish", "tur"),
//    TWI("App.Language.Twi", "twi"),
//    UIGHUR("App.Language.Uighur", "uig"),
//    UKRAINIAN("App.Language.Ukrainian", "ukr"),
//    URDU("App.Language.Urdu", "urd"),
//    UZBEK("App.Language.Uzbek", "uzb"),
//    VENDA("App.Language.Venda", "ven"),
//    VIETNAMESE("App.Language.Vietnamese", "vie"),
//    VOLAPüK("App.Language.Volapük", "vol"),
//    WALLOON("App.Language.Walloon", "wln"),
//    WOLOF("App.Language.Wolof", "wol"),
//    XHOSA("App.Language.Xhosa", "xho"),
//    YIDDISH("App.Language.Yiddish", "yid"),
//    YORUBA("App.Language.Yoruba", "yor"),
//    CHINESE_CANTONESE("App.Language.Chinese-Cantonese", "yue"),
//    ZHUANG("App.Language.Zhuang", "zha"),
//    CHINESE_CHINA("App.Language.Chinese-China", "zho"),
//    CHINESE_TAIWAN("App.Language.Chinese-Taiwan", "zhtw"),
//    ZULU("App.Language.Zulu", "zul");

//    ALBANIAN("App.Language.Albanian", "sq", Set.of("alb", "sq", "Albanian")),
//    ARABIC("App.Language.Arabic", "ar", Set.of("ara", "Arabic")),
//    ARMENIAN("App.Language.Armenian", "hy", Set.of("arm", "hye", "Armenian")),
//    AZERBAIJANI("App.Language.Azerbaijani", "az", Set.of("aze", "Azerbaijani")),
//    BELARUSIAN("App.Language.Belarusian", "be", Set.of("bel", "Belarusian")),
//    BENGALI("App.Language.Bengali", "bn", Set.of("ben", "Bengali")),
//    BOSNIAN("App.Language.Bosnian", "bs", Set.of("bos", "Bosnian")),
//    BULGARIAN("App.Language.Bulgarian", "bg", Set.of("bul", "Bulgarian")),
//    CANTONESE("App.Language.Cantonese", "yue", Set.of("Yuet", "Cantonese")),
//    CATALAN("App.Language.Catalan", "ca", Set.of("cat", "Catalan")),
//    CHINESE_SIMPLIFIED("App.Language.Chinese_simplified", "zh", Set.of("chi", "zho", "Chinese")),
//    CHINESE_TRADITIONAL("App.Language.Chinese_traditional", "zh", Set.of("chi", "zho", "Chinese")),
//    CROATIAN("App.Language.Croatian", "hr", Set.of("hrv", "Croatian")),
//    CZECH("App.Language.Czech", "cs", Set.of("cze", "ces", "Czech")),
//    DANISH("App.Language.Danish", "da", Set.of("dan", "Danish")),
//    DUTCH("App.Language.Dutch", "nl", Set.of("dut", "nld", "ned", "Dutch")),
//    ENGLISH("App.Language.English", "en", Set.of("eng", "english")),
//    ESTONIAN("App.Language.Estonian", "et", Set.of("est", "Estonian")),
//    EUSKERA("App.Language.Euskera", "eu", Set.of("Euskera")),
//    FINNISH("App.Language.Finnish", "fi", Set.of("Fin", "Finnish")),
//    FRENCH("App.Language.French", "fr", Set.of("fre", "fra", "French")),
//    GALICIAN("App.Language.Galician", "gl", Set.of("glg", "Galician")),
//    GERMAN("App.Language.German", "de", Set.of("ger", "deu", "German")),
//    GREEK("App.Language.Greek", "el", Set.of("gre", "ell", "Greek")),
//    HEBREW("App.Language.Hebrew", "he", Set.of("heb", "Hebrew")),
//    HINDI("App.Language.Hindi", "hi", Set.of("hin", "Hindi")),
//    HUNGARIAN("App.Language.Hungarian", "hu", Set.of("hun", "Hungarian")),
//    ICELANDIC("App.Language.Icelandic", "is", Set.of("ice", "isl", "Icelandic")),
//    INDONESIAN("App.Language.Indonesian", "id", Set.of("ind", "Indonesian")),
//    IRISH("App.Language.Irish", "ga", Set.of("gle", "Irish")),
//    ITALIAN("App.Language.Italian", "it", Set.of("ita", "Italian")),
//    JAPANESE("App.Language.Japanese", "ja", Set.of("jpn", "Japanese")),
//    KANNADA("App.Language.Kannada", "ka", Set.of("kan", "Kannada")),
//    KLINGON("App.Language.Klingon", "tlh", Set.of("Klingon")),
//    KOREAN("App.Language.Korean", "ko", Set.of("kor", "Korean")),
//    LATVIAN("App.Language.Latvian", "lv", Set.of("lav", "Latvian")),
//    LITHUANIAN("App.Language.Lithuanian", "lt", Set.of("lit", "Lithuanian")),
//    MACEDONIAN("App.Language.Macedonian", "mk", Set.of("mac", "mkd", "Macedonian")),
//    MALAY("App.Language.Malay", "ms", Set.of("may", "msa", "Malay")),
//    MALAYALAM("App.Language.Malayalam", "ml", Set.of("mal", "Malayalam")),
//    MARATHI("App.Language.Marathi", "mr", Set.of("mar", "Marathi")),
//    NORWEGIAN("App.Language.Norwegian", "no", Set.of("nor", "Norwegian")),
//    PERSIAN("App.Language.Persian", "fa", Set.of("per", "fas", "Persian")),
//    POLISH("App.Language.Polish", "pl", Set.of("pol", "Polish")),
//    PORTUGUESE("App.Language.Portuguese", "pt", Set.of("por", "Portuguese")),
//    ROMANIAN("App.Language.Romanian", "ro", Set.of("rum", "ron", "Romanian")),
//    RUSSIAN("App.Language.Russian", "ru", Set.of("rus", "Russian")),
//    SERBIAN("App.Language.Serbian", "sr", Set.of("srp", "Serbian")),
//    SINHALA("App.Language.Sinhala", "si", Set.of("sin", "Sinhalese", "Sinhala")),
//    SLOVAK("App.Language.Slovak", "sk", Set.of("slo", "slk", "Slovak")),
//    SLOVENIAN("App.Language.Slovenian", "sl", Set.of("slv", "Slovenian")),
//    SPANISH("App.Language.Spanish", "es", Set.of("spa", "Spanish")),
//    SWEDISH("App.Language.Swedish", "se", Set.of("swe", "Swedish")),
//    TAGALOG("App.Language.Tagalog", "tl", Set.of("tgl", "Tagalog")),
//    TAMIL("App.Language.Tamil", "ta", Set.of("tam", "Tamil")),
//    TELUGU("App.Language.Telugu", "te", Set.of("tel", "Telugu")),
//    THAI("App.Language.Thai", "th", Set.of("tha", "Thai")),
//    TURKISH("App.Language.Turkish", "tr", Set.of("tur", "Turkish")),
//    UKRAINIAN("App.Language.Ukrainian", "uk", Set.of("ukr", "Ukrainian")),
//    VIETNAMESE("App.Language.Vietnamese", "vi", Set.of("vie", "Vietnamese")),
//    WELSH("App.Language.Welsh", "cy", Set.of("wel", "cym", "Welsh"));

//    @val String msgCode;
//    @val String langCode;
//    @val Set<String> langCodesOther;
//
//    public static Language fromValue(String value) {
//        return Language.values().stream().filter(lang -> lang.name().equalsIgnoreCase(value)).findAny().orElseThrow();
//    }
//
//    public static Optional<Language> fromValueOptional(String value) {
//        return Language.values().stream().filter(lang -> lang.name().equalsIgnoreCase(value)).findAny();
//    }
//
//    public static Optional<Language> ofLangCodeOptional(String languageId) {
//        return Language.values().stream().filter(lang -> lang.langCode.equalsIgnoreCase(languageId)).findAny();
//    }
//
//    public static Language ofLangCode(String languageId) {
//        return ofLangCodeOptional(languageId).orElseThrow();
//    }
//
//    public String getName() {
//        return name().substring(0, 1).toUpperCase() + name().substring(1).toLowerCase();
//    }
}
