# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        echo "::set-output name=releaseName::`ls home/runner/work/SubTools/SubTools/SubSort/target/subsort-*.jar | awk -F '(/|.jar)' '{print $8}'`"
    - name: Upload jar
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.buildRelease.outputs.releaseName }}
        path: "home/runner/work/SubTools/SubTools/SubSort/target/subsort-*.jar"
