---
name: "pre-release"

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: "./packages/automatic-releases/"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          *.jar
      id: "automatic_releases"

    - name: "Automatically mirror release artifacts"
      env:
        GITHUB_SUPER_TOKEN: ${{ secrets.GITHUB_SUPER_TOKEN }}
      run: |
        ./scripts/mirror-actions.sh "$AUTOMATIC_RELEASES_TAG"
    - uses: "./packages/keybase-notifications"
      if: always()
      with:
        job_status: ${{ job.status }}
        opensentinel_token: ${{ secrets.OSL_TOKEN }}